{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- if and (.Values.global) (.Values.global.mtcil) (.Values.global.mtcil.limaasEnabled) -}}
{{- if .Values.global.mtcil.disableLiSecretProvisioning }}
# LiSecretProvisioning is disabled, create it externally before deploying
# LIMaaS
{{- else }}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: Secret
{{- include "cnfTplMetadata_2_27" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.deployment.pod_metaspec) }}
data:
{{ (.Files.Glob "secret/*").AsSecrets | indent 2 }}
{{- end -}}
{{- end -}}
{{- end }}
