{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- if and (.Values.global) (.Values.global.mtcil) (.Values.global.mtcil.limaasEnabled) -}}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: Service
{{- include "cnfTplMetadata_2_27" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.service.metaspec) }}
    {{- if eq (.Values.global.mtcil.ingress.lbController | toString) "metalLB" }}
    {{- if .Values.ingress.metallb.addressPool }}
    metallb.universe.tf/address-pool: "{{ .Values.ingress.metallb.addressPool | toString }}"
    {{- else }}
    metallb.universe.tf/allow-shared-ip: "{{ .Values.global.nf.mtcilId | toString }}"
    metallb.universe.tf/address-pool: "{{ .Values.global.mtcil.ingress.addressPool | toString }}"
    {{- end }}
    {{- end }}
spec:
  selector:
    app: li-manager
{{- if  .Values.serviceConfig }}
{{ toYaml .Values.serviceConfig | indent 2 }}
{{- end }}
{{- if .Values.global.mtcil.serviceConfig }}
{{ toYaml .Values.global.mtcil.serviceConfig | indent 2 }}
{{- end }}
  ports:
    - port: 443
      targetPort: 4430
{{- if .Values.global.mtcil.ingress.enableLB }}
      nodePort: 0
{{- end }}
      protocol: TCP
      name: https
    - port: 9090
      targetPort: 9090
{{- if .Values.global.mtcil.ingress.enableLB }}
      nodePort: 0
{{- end }}
      protocol: TCP
      name: http
{{- if and (eq (.Values.global.mtcil.ingress.lbController | toString) "metalLB") .Values.global.mtcil.ingress.enableLB }}
  type: "LoadBalancer"
  {{- if .Values.ingress.metallb.lbIngressIP }}
  loadBalancerIP: {{ .Values.ingress.metallb.lbIngressIP }}
  {{- else }}
  loadBalancerIP: {{ .Values.global.mtcil.ingress.lbIngressIP }}
  {{- end }}
{{- else }}
  type: {{ printf "%s" ( ternary "ClusterIP" "NodePort" .Values.global.mtcil.ingress.enableLB ) }}
{{- end }}
{{- end -}}
{{- end }}
