{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- if and (eq (.Values.global.mtcil.ingress.lbController | toString) "istio") .Values.global.mtcil.ingress.enableLB }}
{{- if and .Values.global.mtcil.limaasEnabled .Values.ingress.istio.enabled -}}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: li-manager
  namespace: {{ $cnfHdr.nfVariables.nfPrefix }}
spec:
  hosts:
    - "*"
  gateways:
    - mtcil-https-li-manager
  tls:
    - match:
      - sniHosts:
        - "*"
      route:
        - destination:
            host: li-manager
            port:
              number: 443
{{- end }}
{{- end }}
{{- end }}
 
