{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtcil-sa
  labels:
    app.kubernetes.io/name: mtcil
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ $cnfHdr.nfVariables.nfPrefix }}
{{- if  .Values.global.mtcil.imagePullSecrets }}
imagePullSecrets:
- name: {{ .Values.global.mtcil.imagePullSecrets }}
{{- end }}
{{- end }}
