{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- if .Values.global.mtcil.infra_deploy -}}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.app_name }}-svc
  namespace: {{ $cnfHdr.nfVariables.nfPrefix }}
  labels:
    app: {{ .Values.common.app_name }}
  {{- $custom_extensions := .Values.global.custom_extensions | default dict -}}
  {{- if $custom_extensions.labels -}}
  {{- range $key, $value := .Values.global.custom_extensions.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if $custom_extensions.annotations }}
  annotations:
  {{- range $key, $value := .Values.global.custom_extensions.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.svc_type }}
  ports:
  - port: {{ .Values.service.ports.broker }} 
    name: broker
  - port: {{ .Values.service.ports.http }} 
    name: http
  selector:
    app: {{ .Values.common.app_name }}
{{- end }}
{{- end }}
