apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: helmrepo
  namespace: flux-system
spec:
  interval: 5m0s
  chart: ./clusters/helm/nginx-test/
  valuesFiles:
    - values.yaml
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: flux-system
