global:
  __ClusterExtIP: 10.69.201.157                                                #Please Update the Cluster Master node IP
  hub: public.ecr.aws/a6u6k4n0
  #timezone: "UTC"
  dnPrefix: mvnr-aws-du
  nf:
    nfId: mtcil
    mtcilId: mtcil1
  mtcil:
    #volumeClaimMetadata:
    #  annotations:
    #    robin.io/replication: "3"
    #    robin.io/faultdomain: "host"
    #    robin.io/runAsAny: "true"

    #clusterDomain: paco-cp.cluster.maz             #Only Update if you need the Custom Domain Feature

    #enableMgmtConfigmapProvisioning: false         #only in case of gitops mode we need this flag

    #enablePodmonitorProvisioning: false       #Please comment it out and use mmaas:true before 22.3.x , if this flag is enabled mmaas should be false.

    #includeFQDNHB: "true"    #MTCIL will send CMaaS and FMaaS service FQDN in the heartbeat. Only in mtcil and cms in same cluster.
    
    k8s_nf_labels: "SiteId,NfName,cnfc_uuid"       #Cutomer Specific-If Kubernetes Labels in VES Events please uncomment below entry.

    cim:
      imageTag: 23.3.1-p5                             #Please Update the image tag based on the patch
      host_path: /data/logs
      #mount_type: DirectoryOrCreate

    svcInit:
      imageTag: 23.3.1-p2                             #Please Update the image tag based on the patch

    #event_label_tmaas_prefix: "mtcil.com/tmaas."
    #event_labels_to_be_prefixed: "nfName,nfServiceName,nfServiceInstanceName"

    imagePullSecrets: artifactory-secret-mtcil       #Update the secret name accordingly
    imagePullPolicy: IfNotPresent     #IfNotPresent/Always
    
    helmTest:
      enable: false

    podConfig:
      dnsConfig:
        options:
          - name: ndots
            value: "2"

    #tolerations:
    #- key: "node.kubernetes.io/unreachable"
    #  operator: "Exists"
    #  effect: "NoExecute"
    #  tolerationSeconds: 10
    #- key: "node.kubernetes.io/unreachable"
    #  operator: "Exists"
    #  effect: "NoExecute"
    #  tolerationSeconds: 10
        
    use_release_ns: true
    create_ns: false
    infra_deploy: true
    infraNodeSelector:
      enabled: true
      labelKey: infra
      labelValue: "true"
    mgmtNodeSelector:
      enabled: true
      labelKey: mgmt
      labelValue: "true"
    kafka_svc_fqdn: "kafka-svc.mtcil.svc.cluster.local:9092"
    etcd_svc_fqdn: "etcd.mtcil.svc.cluster.local:2379"
    zk_svc_fqdn: "zk-0.zk.mtcil.svc.cluster.local:2181"
      #zk_svc_fqdn: "zk-0.zk.mtcil.svc.cluster.local:2181,zk-1.zk.mtcil.svc.cluster.local:2181,zk-2.zk.mtcil.svc.cluster.local:2181"

    #NOTE Only If your mtcil namespace is started with number like below namespace(5gc-mtcil), comment the above fqdn section and below section(fqdn) can be enabled and use it
    #kafka_svc_fqdn: 'kafka-svc.5gc-mtcil.svc.cluster.local:9092'    #Update the name of your namespace in place of 5gc-mtcil 
    #etcd_svc_fqdn: 'etcd.5gc-mtcil.svc.cluster.local:2379'          #Update the name of your namespace in place of 5gc-mtcil
    #zk_svc_fqdn: 'zk.5gc-mtcil.svc.cluster.local:2181'              #Update the name of your namespace in place of 5gc-mtcil

    config_mode: netconf                     # Option are netconf/gitops/mixed
    limaasEnabled: false

    #logging_mode: STDOUT                     #Update the Logging Mode
    #log_format: "unified-json"                #set values as text/json/unified-json when STDOUT is enabeld.
    #logging_stdout_local: true               #Update the Logging local when STDOUT is enabeld.




    storage_engine: zookeeper
    storage:
      storageClass: prometheus-pv
      isProviderMTCIL: false
      mtcilIdPrefixed: false
      mtcilLocalStorageHostPathPrefix: /data
#      hostlocalVolumeSelector:
#        - worker1
#        - worker2
#        - worker3



##OCP-Specific Changes
##NOTE : This value is configurable as per OCP cluster, these are not standard values.
##please check with OCP admin on which values needs to be used in place of 1000880000

    #serviceConfig:
    #  ipFamilyPolicy: PreferDualStack
    #  ipFamilies:
    #    - IPv4
    #    - IPv6
    
    #securityPolicy:
      #type: "scc"
      #name: "restricted-cat-1"  #restricted-cat-1/privileged(privileged only in case of host access is available)

    #podConfig:
      #securityContext:
        #fsGroup: 1000880000  
 
    #containerConfig:
      #securityContext:
        #allowPrivilegeEscalation: false            #if securityPolicy is privileged then make it true
        #capabilities:
          #drop:
            #- all
        #privileged: false          #if securityPolicy is privileged then make it true
        #runAsNonRoot: true
        #runAsUser: 1000880000
        #runAsGroup: 1000880000 


        
##RBAC Mode
    enableRBACprovisioning: true
    scope:
      namespaced: false
      namespaceList:                               #Update the name of your namespaces under namespace list
        - mtcil
      enableNamespaceListRBAC: false
      enablePriviledgedRBAC: true

##WEBHOOK
    enableWebhookprovisioning: true
    #authManagement:
      #enableAutoInjection: false
      #enableSecretDiscovery: true
      #secretName: mtcil-ca-bundle
      #serverKey: tls.key
      #serverCertificate: tls.crt
      #enableCertificateprovisioning: false
      #mtcilWebhookAnnotations:
      #type: "ocp"  #ocp/certmanager
      #ocpApiPrefix: "service.beta.openshift.io"
      

##Ingress-Controller
    ingress:
      enableLB: false
      lbIngressIP: '172.3.4.5'                #Update the External IP 
      lbL7ingressPort: 80                   #The lbL7ingressPort ingress K8S service HTTP port (FMaaS REST port.).
      lbL7tmaasPort: 3179                   #The lbL7tmaasPort ingress K8S service TCP port (TMAAS REST port).
      lbL7fmaasPort: 3179
      lbL4netconfPort: 3181                 #The lbL4netconfPort ingress K8S service TCP port (CMaaS NETCONF port).
      lbL4limaasPort: 3182
      lbL4prometheusPort: 3183
      lbController: "Traefik"                 #Possible values Traefik/metalLB/istio
      #addressPool: "mtcil-address-pool"     #addressPool indicates the address pool name for metalLB.
      istio:                                #This section is required for istio to put ip based on label.
        ingressTcpPort: 3181
        ingressSelector:
          istio: "ingressgateway"

mtcil-infra:
  etcd:
    #app_name_prefix: "st-mtcil-etcd"
    container:
      replica_count: 1
      #image:
        #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
      resource:
        limit_memory: 1000Mi
        limit_cpu: 1000m
        requests_memory: 1000Mi
        requests_cpu: 1000m
    volume:
      storageClaim: 20Gi
      storageCapacity: 20Gi
      
  kafka:
    #app_name_prefix: "st-mtcil-kafka"
    #zk_app_name_prefix: "st-mtcil-zk"
    container:
      replica_count: 1
      #image:
        #tag: v3.4.0                                          #Please Update the image tag based on the patch, if none please comment it out
      resource:
        limit_memory: 2000Mi
        limit_cpu: 1000m
        requests_memory: 2000Mi
        requests_cpu: 1000m
    volume:
      storageClaim: 50Gi
      storageCapacity: 50Gi
  zk:
    #app_name_prefix: "st-mtcil-zk"
    container:
      replica_count: 1
      #image:
        #tag: v3.6.5                                          #Please Update the image tag based on the patch, if none please comment it out
      resource:
        limit_memory: 2000Mi
        limit_cpu: 1000m
        requests_memory: 2000Mi
        requests_cpu: 1000m
    volume:
      storageClaim: 10Gi
      storageCapacity: 10Gi

mtcil-mgmt:
#  li-manager:
#    #ingress:
#      #metallb:
#          #addressPool: mtcil-li-manager-pool
#          #lbIngressIP: 10.x.x.x
#    #app_name_prefix: "st-mtcil-li-manager"
#    #aws_region: us-east-1     ## Enable only if required and it is only specific for AWS system
#    default_destinations_reqd: false
#    x1_1_encrypt_enabled: false       ##For Li X1_1 encryption enable(true) or disable(false)
#    li:                               ##To Enable Log level while installation of LI manager
#      log_level: "ALL"
#    li_manager:
#      #image:
#         #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
#    udsf_add:  "http://udsf-core.mvnr-mtcil1-appln-udsf-udsf1:3000" #<UDSF url needs to updated as per setup>
#    network:
#      #type: ipvlan                                               # Enable accordingly like macvlan/ipvlan etc.,
#      spec:
#        config:
#          master: eth1                                                                       #<Host Interface> #Eg: eth0,eth1
#          mode: l2                                                                           #<Mode> #Eg: l2, bridge
#          ipam:
#            type: host-local
#            ranges:
#            - - gateway: 10.9.100.1
#                rangeEnd: 10.9.100.130
#                rangeStart: 10.9.100.121
#                subnet: 10.9.100.0/24
#  li-proxy:
#    #app_name_prefix: "st-mtcil-li-proxy"
#    #aws_region: us-east-1     ## Enable only if required and it is only specific for AWS system
#    li_proxy:
#      #image:
#         #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
#    network:
#      #type: ipvlan                                                    # Enable accordingly like macvlan/ipvlan etc.,
#      spec:
#        config:
#          master: eth2                                                                          #<Host Interface> #Eg: eth0,eth1
#          mode: l2                                                                          #<Mode> #Eg: l2, bridge
#          ipam:
#            type: host-local
#            ranges:
#            - - gateway: 10.9.17.1
#                rangeEnd: 10.9.17.148
#                rangeStart: 10.9.17.140
#                subnet: 10.9.17.0/24

 
  config-service:
    #volumeClaimMetadata:
    #  annotations:
    #    robin.io/replication: "3"
    #    robin.io/faultdomain: "host"
    #    robin.io/runAsAny: "true"

    #app_name_prefix: "st-mtcil-config-service"
    config_service:
      container:
        #image:
          #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
        resource:
          limit_memory: 1000Mi
          limit_cpu: 1000m
          request_memory: 1000Mi
          request_cpu: 1000m
    oam_sidecar:
      container:
        resource:
          limit_memory: 200Mi
          limit_cpu: 120m
          request_memory: 200Mi
          request_cpu: 120m
    volume:
      storage: 1Gi
  
  tmaas:
    #app_name_prefix: "st-mtcil-tmaas"
    componentSpec:
      deployment:
        #replicas: 1
        tmaas:
          #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
          resource:
            limit_memory: 750Mi
            limit_cpu: 500m
            request_memory: 750Mi
            request_cpu: 500m
        cim:
          resource:
            limit_memory: 200Mi
            limit_cpu: 120m
            request_memory: 200Mi
            request_cpu: 120m
  tpaas:
    #app_name_prefix: "st-mtcil-tpaas"
    #replica_count: 1
    tpaas_service:
      #analytic_kafka_brokers: <kafka-url>              #Only one Broker IP supported
      #schema_registry_url: <schemaregistry-url>        #Only one schemaregistry IP supported
      container:
        #image:
          #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
        resource:
          limit_memory: 1000Mi
          limit_cpu: 500m
          request_memory: 1000Mi
          request_cpu: 500m
    oam_sidecar:
      container:
        resource:
          limit_memory: 500Mi
          limit_cpu: 200m
          request_memory: 500Mi
          request_cpu: 200m

  fmaas:
    #app_name_prefix: "st-mtcil-fmaas"
    #replicaCount: 1
    data:
     createClearEventId: "different"             #same/different(default)
     MTCILInfo:
       MGMT_IP: "10.69.201.157"                                          #Update MTCIL running cluster master node IP for CMS to connect to MTCIL
     collectorDetails:
     - id : 1
       primaryCollector:
         fqdn: 172.21.17.213    #Sample 172.20.202.30
         port: 9095
         secure: true
         passphrase: mypassphrase
         nbiFormat: VES
         nbiType: KAFKA
         kafkaBrokers:
         - 172.21.17.213:9095
         kafkaTopic: mtcil-heartbeat-events
         heartbeat: true
     - id : 2
       primaryCollector:
         fqdn: 172.21.17.213   #Sample 172.20.202.30
         port: 9095
         secure: true
         passphrase: mypassphrase
         nbiFormat: VES
         nbiType: KAFKA
         kafkaBrokers:
         - 172.21.17.213:9095
         kafkaTopic: mtcil-fault-events
         heartbeat: false
     - id : 3
       primaryCollector:
         fqdn: 172.21.17.213    #Sample 172.20.202.30
         port: 9095
         secure: true
         passphrase: mypassphrase
         nbiFormat: VES
         nbiType: KAFKA
         kafkaBrokers:
         - 172.21.17.213:9095
         kafkaTopic: mtcil-tca-events
         heartbeat: false
     - id : 4
       primaryCollector:
         fqdn: 172.21.17.213    #Sample 172.20.202.30
         port: 9095
         secure: true
         passphrase: mypassphrase
         nbiFormat: VES
         nbiType: KAFKA
         kafkaBrokers:
         - 172.21.17.213:9095
         kafkaTopic: mtcil-notification-events
         heartbeat: false
     - id: 5                   #MTCIL to SDAAS Over REST Interface
       primaryCollector:
         fqdn: 172.21.17.213
         port: 9999
         secure: false
         passphrase: mypassphrase
         nbiFormat: VES
         nbiType: REST
         heartbeat: false

#     - id : 6
#       primaryCollector:
#         fqdn: x.x.x.x    #Sample 172.20.202.30
#         port: 9002
#         secure: true
#         passphrase: mypassphrase
#         nbiFormat: VES
#         nbiType: KAFKA
#         kafkaBrokers: [ 172.20.202.31:32704 ]   #XA KAFKA IP
#         kafkaTopic: raw_mtcil_events
#         heartbeat: false

##All settings below would be based on the collector and should be obtained from collector team.
#     - id: 7
#       primaryCollector:
#         fqdn: x.x.x.x
#         port: 9002
#         secure: true
#         passphrase: mypassphrase
#         nbiFormat: VES
#         nbiType: KAFKA
#         kafkaBrokers: [ 172.20.202.32:32705, 172.20.202.32:32706, 172.20.202.32:32707 ]
#         #- kafka-svc.cms.svc.cluster.local:9092
#         #["[fd00:4888:2000:1401::20]:32705", "[fd00:4888:2000:1401::20]:32706", "[fd00:4888:2000:1401::20]:32707"]
#         kafkaTopic: kafka-topic
#         heartbeat: false            #added collector id to required vesdomains as needed
    ##filtering
#         ruleList:
#           - id: 1
#             name: sanity1
#             description: rule-sanity
#             action: allow
#             status: enabled
#             ruleDetails:
#               - ruleId: 1
#                 ruleName: cond1
#                 ruleDescription: condition1-sanity
#                 rule:
#                   field: eventName
#                   value: EVENT1
#                   compareOper: ==
#                   status: enabled
#                 ruleOper: "&&"
#               - ruleId: 2
#                 ruleName: cond2
#                 ruleDescription: condition2-sanity
#                 rule:
#                   field: nfcNamingCode
#                   value: test-appa-noha
#                   compareOper: ==
#                   status: enabled
#                 ruleOper: "&&"

     vesdomains:
       fault:
         collectorList:
           - id: 2
       tca:
         collectorList:
           - id: 3
       notification:
         collectorList:
           - id: 4
           - id: 5
           #- id: 6
           #- id: 7

    oam_sidecar:
      container:
        resource:
          limit_memory: 200Mi
          limit_cpu: 120m
          request_memory: 200Mi
          request_cpu: 120m

    fmaas:
      container:
        #image:                 #Please Update the image tag based on the patch, if none please comment it out
           #tag: 23.x.x_px  
        resource:
          limit_memory: 500Mi
          limit_cpu: 500m
          request_memory: 500Mi
          request_cpu: 500m
  mmaas-controller:
    control_prometheus_conf: disable
    ipVersion: IPV4
    mmaas_enabled: true              
    mtcil_global_scrape_interval: 1m
    mtcil_metric_storage: disable
    mtcil_prometheus: enable
    mtcil_scrape_level: nf
    mutiple_remote_storage: enable
    namespace: mtcil
    operator_namespace: mwppaas
    pod_monitor_selector: release=kube-prometheus-stack
    prom_rule_selector: app=kube-prometheus-stack,release=kube-prometheus-stack
    promcmap_retrycount: 120
    prometheus_crd_name: kube-prometheus-stack-prometheus
    prometheus_operator: disable
    scrape_namespace: any
    server_configmap: mtcil-prometheus-server
    resource:
      request_memory: 200Mi
      request_cpu: 100m
      limit_memory: 200Mi
      limit_cpu: 100m
    #image:
      #tag: 23.x.x_px                                          #Please Update the image tag based on the patch, if none please comment it out
  prometheus:  
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: false
    server:
      enabled: false
      
