{{- if and .Values.global.mtcil.enableServiceprovisioning .Values.global.mtcil.enableMandatoryServices }}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_27" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: v1
kind: Service
{{- include "cnfTplMetadata_2_27" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.service.metaspec) }}
    {{- if eq (.Values.global.mtcil.ingress.lbController | toString) "metalLB" }}
    metallb.universe.tf/allow-shared-ip: "{{ .Values.global.nf.mtcilId | toString }}"
    metallb.universe.tf/address-pool: "{{ .Values.global.mtcil.ingress.addressPool | toString }}"
    {{- end }}
    {{- if and .Values.global.mtcil.authManagement.enableAutoInjection (eq (.Values.global.mtcil.authManagement.type | toString) "ocp") }}
    {{ .Values.global.mtcil.authManagement.ocpApiPrefix }}/serving-cert-secret-name: "config-service"
    {{- end }}
spec:
  selector:
    app: config-service
{{- if  .Values.serviceConfig }}
{{ toYaml .Values.serviceConfig | indent 2 }}
{{- end }}
{{- if .Values.global.mtcil.serviceConfig }}
{{ toYaml .Values.global.mtcil.serviceConfig | indent 2 }}
{{- end }}
  ports:
  - name: netconf
    {{- if and (eq (.Values.global.mtcil.ingress.lbController | toString) "metalLB") .Values.global.mtcil.ingress.enableLB }}
    port: {{ .Values.global.mtcil.ingress.lbL4netconfPort }}
    {{- else }}
    port: 12090
    {{- end }}
    targetPort: 2022
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: cli
    port: 10090
    targetPort: 2024
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: ssh
    port: 13090
    targetPort: 22
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: ipc
    port: 15090
    targetPort: 4565
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: restconf
    port: 8008
    targetPort: 8008
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: http-app
    port: 9091
    targetPort: 9091
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: webhook
    port: 443
    targetPort: 8443
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  - name: actuator
    port: 9092
    targetPort: 9092
  {{- if .Values.global.mtcil.ingress.enableLB }}
    nodePort: 0
  {{- end }}
  {{- if and (eq (.Values.global.mtcil.ingress.lbController | toString) "metalLB") .Values.global.mtcil.ingress.enableLB }}
  type: "LoadBalancer"
  loadBalancerIP: {{ .Values.global.mtcil.ingress.lbIngressIP }}
  {{- else }}
  type: {{ printf "%s" ( ternary "ClusterIP" "NodePort" .Values.global.mtcil.ingress.enableLB ) }}
  {{- end }}
  {{- end }}
