######## CNF TEMPLATE DEFINITIONS ###########

nf:
  version: "23.3.1-p3"
  vendorId: "mvnr"
  mtcilId: "mtcil1"
  nfClass: "mgmt"
  nfType: "mtcil"
  nfId: "mtcil1"
  cnftpl_configmap:
    mgmt_cfg:
      create: true
      metaspec:
        annotations:
          configMgmt: enabled
    static_cfg:
      create: true 
      metaspec: {}
    env_cfg:
      create: false
      metaspec: {}
  cnftpl_secret:
      create: false
      metaspec: {}
      secretspec: {}
  cnftpl_namespaces:
      create: false
      metaspec: {}
  cnftpl_dashboard:
      create: false
      metaspec: {}
  cnftpl_eventdef:
      create: true 
      metaspec: {}
  cnftpl_alertsdef:
      create: false
      metaspec: {}
  cnftpl_metricsdef:
      create: false
      metaspec: {}

app_name_prefix: ""
###########################################

namespace: mvnr-mtcil1-mgmt-mtcil-mtcil1
operator_name: OPERATOR
product_name: 5GC
#Keep value for mdf2_server_name as "" to support ICF along with MDF2
mdf2_server_name: li-proxy.mtcil
x1_1_encrypt_enabled: true
list_of_nfs: "amf1,smf1"
cli_tls_min_ver: 1.2
cli_tls_max_ver: 1.3
mtls_enabled: true
# aws_region: "us-east-1" #Use it for AWS environment only

hub: 10.1.34.105:5000

kafka_svc_fqdn: "kafka-svc.mvnr-mtcil1-infra-mtcil-mtcil1:9092"

common:
  app_name: li-proxy

replica_count: 1

componentSpec:
  deployment:
    pod_metaspec:
      labels:
        app: li-proxy
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        k8s.v1.cni.cncf.io/networks: li-proxy-macvlan-conf-1

  service:
    metaspec:
      labels:
        app: li-proxy

li_proxy:
  image:
    hub: 10.1.34.105:5000
    repository: li-proxy
    tag: 23.3.1-p3
    pullPolicy: Always 
  resource:
    limit_memory: 500Mi
    limit_cpu: 200m
    request_memory: 100Mi
    request_cpu: 100m
  containerConfig:
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
      privileged: false
  init_container:
    image:
      repository: mtcil-svc-init
      tag: 21.2.2
  li_proxy_brokers: kafka-svc.mvnr-mtcil1-infra-mtcil-mtcil1:9092
  num_partitions: 50
  replication_factor: 1
  kafka_topic_name_2g: "XIRI.SGSN"
    
cim:
  container:
    hostname: cim
    image:
      repository: cim
      tag: 21.2.2
    resource:
      limit_memory: 500Mi
      limit_cpu: 200m
      request_memory: 100Mi
      request_cpu: 100m
    ports: 
      server: 4222
    mount:
      type: DirectoryOrCreate
      container_path: /opt/logs
      host_path: /data/logs

li_x2:
  time_p1: 60
  time_p2: 180
  n_retry: 3
  report_periodicity: 180
  storage_volume_threshold: 80
  retain_iri_period: 36   # IRI retention period in hours
  udsf_address: "http://udsf-core.mvnr-mtcil1-appln-udsf-udsf1:3000"
  ipsec_enabled: true

li_x2_gen:
  log_level: "ERROR"

network:
  componentSpec:
    deployment:
      network_metaspec:
        ext_name: macvlan-conf-1
        labels:
          app: iked
  apiVersion: k8s.cni.cncf.io/v1 #use robin.io for robin bundle
  cniVersion: 0.3.0
  type: macvlan

#  spec:
#    config:
#      ipam:
#        datastore: kubernetes
#        kubernetes:
#          kubeconfig: /etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig
#        ranges:
#        - - gateway: 172.51.1.1
#            rangeEnd: 172.51.1.50
#            rangeStart: 172.51.1.30
#            subnet: 172.51.1.0/24
#        type: whereabouts
#      master: eth1
#      mode: bridge

podConfig:

affinity:
  nodeAffinity: {}
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: component
            operator: In
            values:
            - "li-proxy"
        topologyKey: kubernetes.io/hostname
