annotations:
  charts.openshift.io/name: mtcil
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Li-Manager.
kubeVersion: '>= 1.16.0-0'
maintainers:
- email: support@mavenir.com
  name: mtcil team
name: li-manager
version: 23.3.1-p5
